name: React App CICD

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.0 

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Install dependencies
        run: npm i

      - name: Compile project
        run: npm run build

      - name: Upload the built file
        uses: actions/upload-artifact@v6.0.0
        with:
           name: react build
           path: ./dist

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.0

      - name: Download the build file
        uses: actions/download-artifact@v7.0.0
        with:
          name: react build

      - name: Run tests
        run: npm run test

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.0

      

